const D=RTG;
let S=JSON.parse(localStorage.getItem("RTG_SAVE")||"null")||{league:null,team:null,season:1,games:[],page:"home",difficulty:"Pro"};
const save=()=>localStorage.setItem("RTG_SAVE",JSON.stringify(S));
const T=()=>D[S.league]||[];
const TN=c=>(T().find(x=>x[0]===c)||[c,c])[1];
const P=()=>((D.players[S.league]||{})[S.team]||[]);
const target=()=>S.league==="NBA"?82:17;
const wins=()=>S.games.filter(g=>g.win).length;
const losses=()=>S.games.filter(g=>!g.win).length;
function nav(p){S.page=p;save();render()}
function reset(){if(confirm("Delete this franchise and start over?")){S={league:null,team:null,season:1,games:[],page:"home",difficulty:"Pro"};save();render()}}
function choose(l){S.league=l;S.page="teams";save();render()}
function start(c){S.team=c;S.games=[];S.page="dashboard";save();render()}
function opp(){let x=T().filter(t=>t[0]!==S.team);return x[Math.floor(Math.random()*x.length)]}
function teamPower(c){let ps=(D.players[S.league]||{})[c]||[];if(!ps.length)return 78;return ps.reduce((a,p)=>a+Number(p[2]),0)/ps.length}
function play(){if(S.games.length>=target()){alert("Season complete.");return}let o=opp(), own=teamPower(S.team), other=teamPower(o[0]);let base=S.league==="NBA"?.67:.60;let chance=Math.max(.08,Math.min(.92,base+(own-other)*.012));if(S.difficulty==="Easy")chance+=.08;if(S.difficulty==="Legend")chance-=.08;let win=Math.random()<chance;let score;if(S.league==="NBA"){let a=Math.round(96+Math.random()*25+own*.05),b=Math.round(96+Math.random()*25+other*.05);if(win&&a<=b)a=b+Math.floor(Math.random()*8)+1;if(!win&&a>=b)b=a+Math.floor(Math.random()*8)+1;score=`${a}-${b}`}else{let a=Math.round(17+Math.random()*18+own*.06),b=Math.round(17+Math.random()*18+other*.06);if(win&&a<=b)a=b+1+Math.floor(Math.random()*10);if(!win&&a>=b)b=a+1+Math.floor(Math.random()*10);score=`${a}-${b}`}S.games.push({n:S.games.length+1,opp:o[0],win,score});save();render()}
function home(){return `<div class="hero"><div><div class="eyebrow">Road to Greatness</div><h1>Chase<br>Perfect.</h1><p>Build a franchise and try to survive an entire NBA or NFL season without losing. This version adds franchise dashboards, player ratings, game plans, stats, standings and a real save system.</p><div class="buttons"><button class="btn" onclick="choose('NBA')">🏀 NBA 82–0</button><button class="btn alt" onclick="choose('NFL')">🏈 NFL 17–0</button></div></div></div><div class="wrap"><div class="cards"><div class="card"><div class="eyebrow">NBA</div><h2>82 Games</h2><p class="muted">Try to become the first team in your franchise save to finish 82–0.</p></div><div class="card"><div class="eyebrow">NFL</div><h2>17 Games</h2><p class="muted">Navigate a full regular season and protect the perfect record.</p></div><div class="card"><div class="eyebrow">Built to expand</div><h2>Franchise Engine</h2><p class="muted">The game is structured so rosters, contracts, injuries, trades, drafts and playoffs can be added without rebuilding the UI.</p></div></div></div>`}
function teams(){return `<div class="wrap"><div class="eyebrow">${S.league}</div><h1>Choose your team</h1><div class="grid">${T().map(t=>`<div class="card click" onclick="start('${t[0]}')"><b>${t[1]}</b><div class="muted">${t[0]} · Power ${Math.round(teamPower(t[0]))}</div></div>`).join("")}</div></div>`}
function dashboard(){let w=wins(),l=losses(),rem=target()-S.games.length;return `<div class="wrap"><div class="eyebrow">${S.league} · SEASON ${S.season}</div><h1>${TN(S.team)}</h1><div class="statgrid"><div class="stat">Record<b>${w}-${l}</b></div><div class="stat">Games left<b>${rem}</b></div><div class="stat">Team rating<b>${Math.round(teamPower(S.team))}</b></div><div class="stat">Goal<b>${target()}–0</b></div></div><div class="buttons"><button class="btn" onclick="play()">Play next game</button><button class="btn alt" onclick="nav('team')">Roster</button><button class="btn alt" onclick="nav('schedule')">Schedule</button><button class="btn alt" onclick="nav('standings')">Standings</button><button class="btn red" onclick="reset()">Reset</button></div><div class="notice">${l===0?"🔥 You're still undefeated. One loss ends the perfect-season chase.":"The perfect-season chase is over, but you can finish the season."}</div></div>`}
function roster(){return `<div class="wrap"><div class="eyebrow">${S.league} ROSTER</div><h1>${TN(S.team)}</h1><div class="card">${P().length?P().map(p=>`<div class="player"><div><b>${p[0]}</b><div class="muted">${p[1]}</div></div><div class="rating">${p[2]}</div></div>`).join(""):`<div class="muted">This team's roster seed is ready for the full data import.</div>`}</div><p class="footer">Player seed ratings are game values, not official league ratings.</p></div>`}
function schedule(){return `<div class="wrap"><div class="eyebrow">SCHEDULE</div><h1>${TN(S.team)}</h1>${S.games.length?S.games.map(g=>`<div class="game"><div>Game ${g.n}<br><span class="muted">Regular Season</span></div><div class="${g.win?'win':'loss'}"><b>${g.win?'W':'L'}</b><br>${g.score}</div><div class="right">vs ${TN(g.opp)}</div></div>`).join(""):`<div class="card muted">No games played. Start the season from the dashboard.</div>`}</div>`}
function standings(){let rows=T().map(t=>{let g=t[0]===S.team?S.games:[];return {t,w:g.filter(x=>x.win).length,l:g.filter(x=>!x.win).length}}).sort((a,b)=>b.w-a.w||a.l-b.l);return `<div class="wrap"><div class="eyebrow">${S.league}</div><h1>Standings</h1><div class="tablebox"><table class="table"><thead><tr><th>#</th><th>Team</th><th>W</th><th>L</th><th>Win %</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${r.t[1]}</td><td class="win">${r.w}</td><td class="loss">${r.l}</td><td>${(r.w+r.l)?(100*r.w/(r.w+r.l)).toFixed(1):"—"}</td></tr>`).join("")}</tbody></table></div></div>`}
function shell(body){return `<header class="top"><div class="logo">ROAD <span>TO</span> GREATNESS</div><nav class="nav"><button onclick="nav('home')">Home</button>${S.league?`<button onclick="nav('dashboard')">Franchise</button><button onclick="nav('team')">Roster</button><button onclick="nav('schedule')">Schedule</button><button onclick="nav('standings')">Standings</button>`:""}</nav></header>${body}<div class="footer">Road to Greatness · browser prototype · save data stays in this browser</div>`}
function render(){let b=S.page==="home"?home():S.page==="teams"?teams():S.page==="dashboard"?dashboard():S.page==="team"?roster():S.page==="schedule"?schedule():standings();document.querySelector("#app").innerHTML=shell(b)}
render();
