(function(){
'use strict';

/* Road to Greatness v6
   Fully self-contained: no CDN, no imports, no external assets.
   Uses a lightweight perspective canvas renderer so the site can deploy on Netlify
   even when third-party scripts are blocked. */

const NBA=[
['ATL','Atlanta Hawks'],['BOS','Boston Celtics'],['BKN','Brooklyn Nets'],['CHA','Charlotte Hornets'],['CHI','Chicago Bulls'],['CLE','Cleveland Cavaliers'],['DAL','Dallas Mavericks'],['DEN','Denver Nuggets'],['DET','Detroit Pistons'],['GSW','Golden State Warriors'],['HOU','Houston Rockets'],['IND','Indiana Pacers'],['LAC','LA Clippers'],['LAL','Los Angeles Lakers'],['MEM','Memphis Grizzlies'],['MIA','Miami Heat'],['MIL','Milwaukee Bucks'],['MIN','Minnesota Timberwolves'],['NOP','New Orleans Pelicans'],['NYK','New York Knicks'],['OKC','Oklahoma City Thunder'],['ORL','Orlando Magic'],['PHI','Philadelphia 76ers'],['PHX','Phoenix Suns'],['POR','Portland Trail Blazers'],['SAC','Sacramento Kings'],['SAS','San Antonio Spurs'],['TOR','Toronto Raptors'],['UTA','Utah Jazz'],['WAS','Washington Wizards']];
const STARS={ATL:['Trae Young','Jalen Johnson','Dyson Daniels','Nickeil Alexander-Walker','Onyeka Okongwu'],BOS:['Jayson Tatum','Jaylen Brown','Derrick White','Jrue Holiday','Kristaps Porzingis'],CLE:['Donovan Mitchell','Darius Garland','Evan Mobley','Jarrett Allen','Max Strus'],DAL:['Cooper Flagg','Anthony Davis','Kyrie Irving','Klay Thompson','Daniel Gafford'],DEN:['Nikola Jokic','Jamal Murray','Aaron Gordon','Michael Porter Jr.','Christian Braun'],DET:['Cade Cunningham','Jalen Duren','Ausar Thompson','Tobias Harris','Malik Beasley'],GSW:['Stephen Curry','Jimmy Butler','Draymond Green','Jonathan Kuminga','Buddy Hield'],HOU:['Kevin Durant','Alperen Sengun','Amen Thompson','Fred VanVleet','Jabari Smith Jr.'],LAL:['Luka Doncic','LeBron James','Austin Reaves','Rui Hachimura','Deandre Ayton'],MIA:['Bam Adebayo','Tyler Herro','Andrew Wiggins','Norman Powell',"Kel'el Ware"],MIL:['Giannis Antetokounmpo','Myles Turner','Kyle Kuzma','AJ Green','Bobby Portis'],MIN:['Anthony Edwards','Julius Randle','Rudy Gobert','Jaden McDaniels','Mike Conley'],NYK:['Jalen Brunson','Karl-Anthony Towns','OG Anunoby','Mikal Bridges','Josh Hart'],OKC:['Shai Gilgeous-Alexander','Jalen Williams','Chet Holmgren','Alex Caruso','Isaiah Hartenstein'],ORL:['Paolo Banchero','Franz Wagner','Desmond Bane','Jalen Suggs','Wendell Carter Jr.'],PHI:['Joel Embiid','Tyrese Maxey','Paul George','Kelly Oubre Jr.','Jared McCain'],PHX:['Devin Booker','Jalen Green','Dillon Brooks','Mark Williams','Grayson Allen'],SAS:['Victor Wembanyama','Devin Vassell','Stephon Castle',"De'Aaron Fox",'Harrison Barnes']};
const POS=['PG','SG','SF','PF','C'];
const ARCH={Sharpshooter:[88,60,72,72,70,55],Slasher:[68,90,68,86,88,60],Playmaker:[75,70,92,90,84,58],'Two-Way':[76,72,70,74,80,90]};
const DEFAULT={screen:'home',player:{name:'My Player',pos:'PG',arch:'Sharpshooter',attrs:[88,60,72,72,70,55]},team:'OKC',year:1,money:0,salary:2500000,overall:78,xp:0,level:1,w:0,l:0,standings:{},rosters:{},transactions:[],schedule:[],gameIndex:0,stats:{gp:0,pts:0,ast:0,reb:0,stl:0,blk:0},championships:0,contractYears:3,morale:75,chemistry:75};
let state=loadState(), game=null, running=false, renderQueued=false;
function clone(x){return JSON.parse(JSON.stringify(x));}
function loadState(){try{const raw=localStorage.getItem('rtg_v6');if(raw){const s=JSON.parse(raw);return Object.assign(clone(DEFAULT),s,{player:Object.assign(clone(DEFAULT.player),s.player||{}),stats:Object.assign(clone(DEFAULT.stats),s.stats||{})});}}catch(e){}return clone(DEFAULT)}
function save(){try{localStorage.setItem('rtg_v6',JSON.stringify(state))}catch(e){}}
const $=id=>document.getElementById(id); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function teamName(id){const x=NBA.find(t=>t[0]===id);return x?x[1]:id}
function seed(){NBA.forEach(([id,n],ti)=>{if(!Array.isArray(state.rosters[id])||state.rosters[id].length<12){const names=STARS[id]||[];state.rosters[id]=[...names,...Array.from({length:12-Math.min(12,names.length)},(_,i)=>`${n.split(' ').pop()} Prospect ${i+1}`)].map((name,i)=>({name,pos:POS[i%5],ovr:Math.max(64,94-i*2),age:20+i%13,years:1+i%4,salary:Math.round((1+i)*1.2e6)}))}if(!state.standings[id])state.standings[id]={w:0,l:0}});if(!Array.isArray(state.schedule)||state.schedule.length!==82)generateSchedule();save()}
function generateSchedule(){const idx=Math.max(0,NBA.findIndex(x=>x[0]===state.team));state.schedule=Array.from({length:82},(_,r)=>{let opp=NBA[(idx+r*7+3)%30][0];if(opp===state.team)opp=NBA[(r+11)%30][0];return{opp,home:r%2===0,played:false,result:null}});state.gameIndex=0}
function go(s){state.screen=s;save();render()}
function nav(title){return `<div class="topbar"><b>ROAD TO GREATNESS</b><span>${title}</span><button onclick="go('home')">MENU</button></div>`}
function render(){if(running)return;seed();const screens={home:()=>`<main class="screen"><section class="hero"><div class="eyebrow">SELF-CONTAINED BASKETBALL CAREER GAME</div><h1>ROAD TO<br>GREATNESS</h1><p>No downloads. No external engines. Built to run directly on Netlify.</p><div class="actions"><button class="btn" onclick="newCareer()">NEW CAREER</button><button class="btn" onclick="go('hub')">CONTINUE</button><button onclick="go('rosters')">LEAGUE</button></div></section></main>`,
creator:()=>`<main class="screen"><div class="layout">${nav('PLAYER BUILDER')}<div class="card"><h2>Create Your Player</h2><input id="nm" value="${esc(state.player.name)}"><select id="pp">${POS.map(x=>`<option ${x===state.player.pos?'selected':''}>${x}</option>`).join('')}</select><div class="grid">${Object.keys(ARCH).map(a=>`<button class="choice" onclick="pickArch('${a}')"><b>${a}</b><span>${ARCH[a].join(' / ')}</span></button>`).join('')}</div><button class="btn" onclick="savePlayer()">START MY CAREER</button></div></div></main>`,
hub:()=>`<main class="screen"><div class="layout">${nav('CAREER HUB')}<div class="grid"><div class="card"><h2>${esc(state.player.name)}</h2><div class="stat">${state.overall} OVR</div><p>${state.player.pos} • ${state.player.arch}</p><p>Year ${state.year} • Level ${state.level}</p></div><div class="card"><h2>${teamName(state.team)}</h2><div class="stat">${state.w}-${state.l}</div><p>Next: ${state.schedule[state.gameIndex]?teamName(state.schedule[state.gameIndex].opp):'Playoffs'}</p><button class="btn" onclick="startGame()">PLAY NEXT GAME</button><button onclick="simulateWeek()">SIMULATE 4 GAMES</button>${state.gameIndex>=82?`<button onclick="runPlayoffs()">START PLAYOFFS</button>`:''}</div><div class="card"><h2>Career</h2><p>${state.stats.gp} GP • ${state.stats.pts} PTS • ${state.stats.ast} AST • ${state.stats.reb} REB</p><button onclick="go('schedule')">SCHEDULE</button><button onclick="go('frontoffice')">FRONT OFFICE</button><button onclick="go('locker')">LOCKER ROOM</button></div><div class="card"><h2>Legacy</h2><div class="stat">${state.championships}</div><p>Championships • $${Math.round(state.money/1e6)}M earned</p></div></div></div></main>`,
schedule:()=>`<main class="screen"><div class="layout">${nav('82-GAME SEASON')}<div class="card"><h2>${teamName(state.team)} Schedule</h2>${state.schedule.slice(Math.max(0,state.gameIndex-2),Math.min(state.gameIndex+18,82)).map((g,i)=>`<div class="row"><span>Game ${Math.max(1,state.gameIndex-2)+i} ${g.home?'vs':'@'} ${teamName(g.opp)}</span><b>${g.played?g.result:'UPCOMING'}</b></div>`).join('')}<button class="btn" onclick="go('hub')">BACK</button></div></div></main>`,
rosters:()=>`<main class="screen"><div class="layout">${nav('NBA LEAGUE')}<div class="roster">${NBA.map(([id,n])=>`<div class="card"><b>${n}</b>${state.rosters[id].slice(0,12).map(p=>`<div class="row"><span>${esc(p.name)} (${p.pos})</span><b>${p.ovr}</b></div>`).join('')}</div>`).join('')}</div></div></main>`,
frontoffice:()=>`<main class="screen"><div class="layout">${nav('FRONT OFFICE')}<div class="grid"><div class="card"><h2>Contract</h2><p>Salary: $${state.salary.toLocaleString()}</p><p>Years left: ${state.contractYears}</p><button class="btn" onclick="extendContract()">NEGOTIATE EXTENSION</button></div><div class="card"><h2>Trades</h2><p>Morale ${state.morale} • Chemistry ${state.chemistry}</p><select id="tradeTeam">${NBA.filter(x=>x[0]!==state.team).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select><button class="btn" onclick="requestTrade()">REQUEST TRADE</button></div><div class="card"><h2>Free Agency</h2>${['Veteran Playmaker','Elite Wing','Rim Protector'].map((x,i)=>`<div class="row"><span>${x}</span><button onclick="signFA(${i})">SIGN</button></div>`).join('')}</div><div class="card"><h2>Transactions</h2>${state.transactions.slice(-10).reverse().map(x=>`<p>${esc(x)}</p>`).join('')||'<p>Nothing yet.</p>'}</div></div></div></main>`,
locker:()=>`<main class="screen"><div class="layout">${nav('LOCKER ROOM')}<div class="locker card"><h2>Locker Room</h2><p>Recovery • film • chemistry • development</p><div class="grid"><button class="choice" onclick="train('shoot')"><b>SHOOTING LAB</b><span>+XP and +shooting</span></button><button class="choice" onclick="train('film')"><b>FILM ROOM</b><span>Improve decision making</span></button><button class="choice" onclick="train('recovery')"><b>RECOVERY</b><span>Boost morale</span></button><button class="choice" onclick="train('team')"><b>TEAM MEETING</b><span>Boost chemistry</span></button></div></div></div></main>`};
$('app').innerHTML=(screens[state.screen]||screens.home)()}

function newCareer(){state=clone(DEFAULT);state.screen='creator';save();render()}
function pickArch(a){state.player.arch=a;state.player.attrs=[...ARCH[a]];state.overall=Math.round(state.player.attrs.reduce((a,b)=>a+b,0)/6);save();render()}
function savePlayer(){state.player.name=$('nm').value.trim()||'My Player';state.player.pos=$('pp').value;state.overall=Math.round(state.player.attrs.reduce((a,b)=>a+b,0)/6);state.screen='hub';seed();save();render()}
function train(x){state.xp+=x==='shoot'?140:90;state.level=1+Math.floor(state.xp/500);if(x==='shoot')state.player.attrs[0]=Math.min(99,state.player.attrs[0]+1);if(x==='recovery')state.morale=Math.min(100,state.morale+8);if(x==='team')state.chemistry=Math.min(100,state.chemistry+8);state.overall=Math.min(99,Math.round(state.player.attrs.reduce((a,b)=>a+b,0)/6));save();render()}
function simulateGame(){const g=state.schedule[state.gameIndex];if(!g)return;const my=state.overall+state.chemistry*.08+Math.random()*18,op=72+Math.random()*24,win=my>op;state.w+=win?1:0;state.l+=win?0:1;state.stats.gp++;const pts=Math.round(10+state.overall*.25+Math.random()*18);state.stats.pts+=pts;state.stats.ast+=Math.floor(Math.random()*7);state.stats.reb+=Math.floor(Math.random()*9);state.stats.stl+=Math.floor(Math.random()*3);state.stats.blk+=Math.floor(Math.random()*2);state.xp+=win?220:110;state.level=1+Math.floor(state.xp/500);state.money+=state.salary/82;g.played=true;g.result=win?'W':'L';state.standings[state.team].w=state.w;state.standings[state.team].l=state.l;state.gameIndex++}
function simulateWeek(){for(let i=0;i<4&&state.gameIndex<82;i++)simulateGame();save();render()}
function extendContract(){state.contractYears+=2;state.salary=Math.round(state.salary*1.12);state.transactions.push(`Signed a ${state.contractYears}-year extension at $${state.salary.toLocaleString()} per year.`);save();render()}
function requestTrade(){const id=$('tradeTeam').value;state.transactions.push(`Trade request: ${teamName(state.team)} → ${teamName(id)}.`);if(Math.random()<.7){state.team=id;state.morale=Math.max(55,state.morale-3);generateSchedule();state.transactions.push(`Trade accepted. Welcome to the ${teamName(id)}.`)}else state.transactions.push('Trade request denied.');save();render()}
function signFA(i){const labels=['Veteran Playmaker','Elite Wing','Rim Protector'];state.transactions.push(`Signed ${labels[i]} depth piece.`);state.chemistry=Math.min(100,state.chemistry+3);save();render()}
function runPlayoffs(){let wins=0;for(let r=0;r<4;r++){if(Math.random()<(0.48+(state.overall-75)*.012))wins++}const champ=wins===4;if(champ)state.championships++;state.transactions.push(champ?'Won the NBA Championship!':`Playoff run ended after ${wins} series win${wins===1?'':'s'}.`);state.year++;state.w=0;state.l=0;state.gameIndex=0;state.contractYears=Math.max(0,state.contractYears-1);state.morale=Math.max(50,state.morale-2);state.chemistry=Math.max(55,state.chemistry-1);generateSchedule();save();go('hub')}

// ---------- Self-contained lightweight perspective renderer ----------
const V=(x=0,y=0,z=0)=>({x,y,z});
function add(a,b){return V(a.x+b.x,a.y+b.y,a.z+b.z)} function sub(a,b){return V(a.x-b.x,a.y-b.y,a.z-b.z)} function mul(a,k){return V(a.x*k,a.y*k,a.z*k)} function len(a){return Math.hypot(a.x,a.y,a.z)} function norm(a){const l=len(a)||1;return mul(a,1/l)} function lerp(a,b,t){return V(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,a.z+(b.z-a.z)*t)} function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function startGame(){if(state.gameIndex>=82){go('hub');return}running=true;const root=document.createElement('main');root.className='game';root.innerHTML=`<canvas id="court" tabindex="0"></canvas><div class="hud"><div><b>ROAD TO GREATNESS</b><span id="score">${teamName(state.team)} 0 — 0 CPU</span></div><div><span id="clock">4:00</span><span id="status">OFFENSE • 5v5</span></div></div><div class="controls">WASD move • SHIFT sprint • SPACE shoot • P pass • E steal • F dunk • ESC exit</div><div class="meter"><div id="meterFill"></div></div><button class="exit" onclick="quitGame()">EXIT</button>`;$('app').innerHTML='';$('app').appendChild(root);const canvas=$('court');canvas.focus();
const ctx=canvas.getContext('2d',{alpha:false}); if(!ctx){running=false;go('hub');return}
const G={canvas,ctx,w:0,h:0,cam:V(-4,7,12),target:V(0,0,0),time:240,us:0,ai:0,poss:'user',cool:0,shot:null,keys:{},last:performance.now(),players:[],ball:V(-5,.5,0),ballVel:V(0,0,0),hasBall:true,streak:0,shotClock:18};game=G;
const userCols=['#56a8ff','#2e80d9','#2b6fbd','#3e92e6','#1d5a9f'], cpuCols=['#ef5964','#d63d49','#b52f3a','#ee7a7f','#a51f2a'];
for(let i=0;i<5;i++){G.players.push({team:'user',i,pos:V(-4+i*1.5,0,(i-2)*2),vel:V(),col:userCols[i],speed:2.2+Math.random()*.4,phase:Math.random()*6,number:i+1}) ;G.players.push({team:'cpu',i,pos:V(4-i*1.5,0,(i-2)*2),vel:V(),col:cpuCols[i],speed:2.0+Math.random()*.4,phase:Math.random()*6,number:i+11})}
G.me=G.players[0]; G.me.pos=V(-4,0,0); G.ball=add(G.me.pos,V(.5,.65,0));
function resize(){G.w=innerWidth;G.h=innerHeight;canvas.width=Math.max(1,Math.floor(innerWidth*devicePixelRatio));canvas.height=Math.max(1,Math.floor(innerHeight*devicePixelRatio));canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();addEventListener('resize',resize);
function keydown(e){const k=e.key.toLowerCase();G.keys[k]=true;if(k===' '){e.preventDefault();shoot()}if(k==='p')pass();if(k==='e')steal();if(k==='f')dunk();if(k==='escape')quitGame()}function keyup(e){G.keys[e.key.toLowerCase()]=false}addEventListener('keydown',keydown);addEventListener('keyup',keyup);G.cleanup=()=>{removeEventListener('keydown',keydown);removeEventListener('keyup',keyup);removeEventListener('resize',resize)};
G.loop=requestAnimationFrame(frame);}
function project(p){const c=game.cam;const r=sub(p,c);const yaw=Math.atan2(r.x,r.z);const cos=Math.cos(yaw),sin=Math.sin(yaw);const z=r.x*sin+r.z*cos;const x=r.x*cos-r.z*sin;const y=r.y;const f=620/(z+18);return{x:game.w/(2)+x*f,y:game.h/(2)-y*f-30,z,scale:f}}
function draw3DLine(a,b,w,color){const A=project(a),B=project(b);game.ctx.strokeStyle=color;game.ctx.lineWidth=Math.max(1,w*(A.scale+B.scale)/2);game.ctx.beginPath();game.ctx.moveTo(A.x,A.y);game.ctx.lineTo(B.x,B.y);game.ctx.stroke()}
function drawPlayer(p){const c=game.ctx, base=p.pos, move=len(p.vel);p.phase+=.12*(move?8:2);const swing=Math.sin(p.phase)*(move?.45:.08), body=add(base,V(0,1.15,0)), head=add(base,V(0,2.05,0));draw3DLine(add(base,V(-.16,.95,0)),add(base,V(-.22,.35,swing)),.13,p.col);draw3DLine(add(base,V(.16,.95,0)),add(base,V(.22,.35,-swing)),.13,p.col);draw3DLine(add(body,V(-.32,.1,0)),add(body,V(-.58,.62,swing)),.11,p.col);draw3DLine(add(body,V(.32,.1,0)),add(body,V(.58,.62,-swing)),.11,p.col);const H=project(head);c.fillStyle='#c98c65';c.beginPath();c.arc(H.x,H.y,Math.max(4,9*H.scale),0,Math.PI*2);c.fill();const B=project(body);c.fillStyle=p.col;c.fillRect(B.x-10*B.scale,B.y-18*B.scale,20*B.scale,25*B.scale);c.fillStyle='#fff';c.font=`bold ${Math.max(8,11*B.scale)}px system-ui`;c.textAlign='center';c.fillText(String(p.number),B.x,B.y-5*B.scale)}
function drawArena(){const c=game.ctx;c.fillStyle='#07101b';c.fillRect(0,0,innerWidth,innerHeight);const corners=[V(-13,0,-7.5),V(13,0,-7.5),V(13,0,7.5),V(-13,0,7.5)];const P=corners.map(project);c.fillStyle='#9b6337';c.beginPath();P.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fill();draw3DLine(V(-13,.03,-7.5),V(13,.03,-7.5),.04,'#fff');draw3DLine(V(-13,.03,7.5),V(13,.03,7.5),.04,'#fff');draw3DLine(V(-13,.03,-7.5),V(-13,.03,7.5),.04,'#fff');draw3DLine(V(13,.03,-7.5),V(13,.03,7.5),.04,'#fff');draw3DLine(V(0,.04,-7.5),V(0,.04,7.5),.035,'#fff');for(const x of [-12.2,12.2]){draw3DLine(V(x,.04,-6),V(x,.04,6),.035,'#fff');draw3DLine(V(x,.04,-6),V(x+(x>0?-5:5),.04,-6),.035,'#fff');draw3DLine(V(x,.04,6),V(x+(x>0?-5:5),.04,6),.035,'#fff');const board=V(x,4.4,0);draw3DLine(board,add(board,V(0,-2.0,0)),.16,'#e8eef5');draw3DLine(add(board,V(0,-.9,-1.7)),add(board,V(0,-.9,1.7)),.08,'#e8eef5');const rim=V(x+(x>0?-1.0:1.0),3.5,0);for(let j=0;j<12;j++){const a=j/12*Math.PI*2,b=(j+1)/12*Math.PI*2;draw3DLine(add(rim,V(0,.05,Math.cos(a)*.65)),add(rim,V(0,.05,Math.cos(b)*.65)),.06,'#ff6b35')}}}
function updateGame(dt){const G=game;if(!G)return;G.time-=dt;if(G.time<=0){finishGame();return}G.cool=Math.max(0,G.cool-dt);const dx=(G.keys.d?1:0)-(G.keys.a?1:0),dz=(G.keys.s?1:0)-(G.keys.w?1:0);let dir=norm(V(dx,0,dz));const speed=G.keys.shift?5.3:3.5;G.me.vel=mul(dir,speed);G.me.pos.x=clamp(G.me.pos.x+dir.x*speed*dt,-11.5,11.5);G.me.pos.z=clamp(G.me.pos.z+dir.z*speed*dt,-6.5,6.5);if(G.hasBall)G.ball=add(G.me.pos,V(.45,.6+Math.abs(Math.sin(performance.now()/110))*.35,0));
const offense=G.poss==='user'?G.players.filter(p=>p.team==='user'):G.players.filter(p=>p.team==='cpu');const defense=G.poss==='user'?G.players.filter(p=>p.team==='cpu'):G.players.filter(p=>p.team==='user');offense.forEach((p,i)=>{if(p===G.me&&G.poss==='user')return;const ang=i*1.257+Math.sin(performance.now()/1300+i)*.25;const hx=G.poss==='user'?10:-10;const target=V(hx*.42+Math.cos(ang)*4.1,0,Math.sin(ang)*5);p.vel=mul(norm(sub(target,p.pos)),p.speed);p.pos=add(p.pos,mul(p.vel,dt))});defense.forEach((p,i)=>{const mark=offense[i%offense.length];let target=lerp(mark.pos,V(G.poss==='user'?9:-9,0,0),.18);if(i===4)target=lerp(target,V(G.poss==='user'?7:-7,0,0),.4);p.vel=mul(norm(sub(target,p.pos)),p.speed);p.pos=add(p.pos,mul(p.vel,dt))});
if(!G.hasBall&&G.shot){G.ball=add(G.ball,mul(G.ballVel,dt));G.ballVel.y-=9.8*dt;if(G.ball.y<.25){G.ball.y=.25;G.ballVel.y*=-.62;G.ballVel.x*=.82;G.ballVel.z*=.82}G.shot.t+=dt;if(len(sub(G.ball,G.shot.target))<.6||G.shot.t>1.7){const made=Math.random()<G.shot.chance;if(made){if(G.shot.type==='user')G.us+=G.shot.pts;else G.ai+=G.shot.pts;G.streak=made?G.streak+1:0}else G.streak=0;G.poss=G.shot.type==='user'?'cpu':'user';G.hasBall=G.poss==='user';G.shot=null;G.shotClock=18}}
if(G.poss==='cpu'&&!G.shot){G.cpuTimer=(G.cpuTimer||0)+dt;if(G.cpuTimer>1.8+Math.random()*1.8){G.cpuTimer=0;const shooter=G.players.filter(p=>p.team==='cpu')[Math.floor(Math.random()*5)];const d=Math.abs(shooter.pos.x+12);const closest=G.players.filter(p=>p.team==='user').reduce((m,p)=>Math.min(m,len(sub(p.pos,shooter.pos))),99);launchFrom(shooter,V(-12,3.5,0),clamp(.42-d*.014-closest*.02,.12,.8),'cpu',d>7?3:2)}}
G.shotClock-=dt;if(G.shotClock<=0&&!G.shot){G.poss=G.poss==='user'?'cpu':'user';G.hasBall=G.poss==='user';G.shotClock=18}
G.cam=lerp(G.cam,add(G.me.pos,V(-5,6,11)),.05);G.target=lerp(G.target,G.me.pos,.08)}
function launchFrom(from,target,chance,type,pts){const G=game;G.hasBall=false;G.shot={target,type,pts,chance,t:0};G.ball=add(from.pos,V(0,1.7,0));const d=sub(target,G.ball);const t=1.05;G.ballVel=mul(d,1/t);G.ballVel.y+=4.8*t}
function shoot(){const G=game;if(!G||!G.hasBall||G.cool>0)return;G.cool=.55;const d=Math.abs(12-G.me.pos.x),def=G.players.filter(p=>p.team==='cpu').reduce((m,p)=>Math.min(m,len(sub(p.pos,G.me.pos))),99);const chance=clamp(.38+state.player.attrs[0]/210-d*.017-def*.018,.08,.9);launchFrom(G.me,V(12,3.5,0),chance,'user',d>7?3:2)}
function dunk(){const G=game;if(!G||!G.hasBall)return;const near=Math.abs(12-G.me.pos.x)<3.0&&Math.abs(G.me.pos.z)<2.2;launchFrom(G.me,V(12,3.5,0),near?.92:.08,'user',2)}
function pass(){const G=game;if(!G||!G.hasBall)return;const mates=G.players.filter(p=>p.team==='user'&&p!==G.me);const mate=mates.sort((a,b)=>len(sub(a.pos,G.me.pos))-len(sub(b.pos,G.me.pos)))[0];G.hasBall=false;G.ball=add(G.me.pos,V(0,1.4,0));G.shot={target:add(mate.pos,V(0,1.3,0)),type:'pass',pts:0,chance:1,t:0};G.ballVel=mul(sub(G.shot.target,G.ball),2.2);setTimeout(()=>{if(game===G&&running){G.hasBall=true;G.shot=null;G.ball=add(mate.pos,V(0,.7,0))}},360)}
function steal(){const G=game;if(!G||G.poss!=='cpu')return;const near=G.players.filter(p=>p.team==='cpu').some(p=>len(sub(p.pos,G.me.pos))<2.3);if(near&&Math.random()<state.player.attrs[5]/115){G.poss='user';G.hasBall=true;G.shot=null;G.streak++}}
function drawGame(){const G=game;if(!G)return;drawArena();const all=[...G.players].sort((a,b)=>a.pos.z-b.pos.z);all.forEach(drawPlayer);const B=project(G.ball);const c=G.ctx;c.fillStyle='#d78338';c.beginPath();c.arc(B.x,B.y,Math.max(5,9*B.scale),0,Math.PI*2);c.fill();c.strokeStyle='#6d3517';c.lineWidth=2;c.stroke();c.fillStyle='#fff';c.font='bold 15px system-ui';c.textAlign='left';c.fillText(`${teamName(state.team)} ${G.us} — ${G.ai} CPU`,18,38);c.textAlign='right';c.fillText(`${Math.floor(G.time/60)}:${String(Math.ceil(G.time%60)).padStart(2,'0')}`,innerWidth-18,38);c.textAlign='center';c.fillText(G.poss==='user'?'OFFENSE • 5v5':'DEFENSE • 5v5',innerWidth/2,38);c.fillStyle='rgba(0,0,0,.45)';c.fillRect(innerWidth/2-120,innerHeight-54,240,10);c.fillStyle='#58a7ff';c.fillRect(innerWidth/2-120,innerHeight-54,240*clamp(state.player.attrs[0]/100,0,1),10);c.font='12px system-ui';c.fillStyle='#fff';c.fillText('WASD • SHIFT • SPACE SHOOT • P PASS • E STEAL • F DUNK',innerWidth/2,innerHeight-68)}
function frame(now){if(!running||!game)return;const dt=Math.min(.033,(now-game.last)/1000);game.last=now;updateGame(dt);drawGame();game.loop=requestAnimationFrame(frame)}
function quitGame(){if(!running)return;running=false;if(game&&game.cleanup)game.cleanup();game=null;go('hub')}
function finishGame(){if(!game)return;running=false;const G=game;const win=G.us>=G.ai;state.w+=win?1:0;state.l+=win?0:1;state.stats.gp++;state.stats.pts+=Math.round(G.us*.8+8);state.stats.ast+=Math.floor(Math.random()*6);state.stats.reb+=Math.floor(Math.random()*8);state.stats.stl+=Math.floor(Math.random()*3);state.stats.blk+=Math.floor(Math.random()*2);state.gameIndex=Math.min(82,state.gameIndex+1);const item=state.schedule[state.gameIndex-1];if(item){item.played=true;item.result=win?'W':'L'}state.money+=state.salary/82;state.xp+=win?220:110;state.level=1+Math.floor(state.xp/500);state.overall=Math.min(99,state.overall+(win&&Math.random()<.15?1:0));save();if(game.cleanup)game.cleanup();game=null;state.screen='hub';render()}

window.go=go;window.newCareer=newCareer;window.pickArch=pickArch;window.savePlayer=savePlayer;window.startGame=startGame;window.simulateWeek=simulateWeek;window.extendContract=extendContract;window.requestTrade=requestTrade;window.signFA=signFA;window.train=train;window.runPlayoffs=runPlayoffs;window.quitGame=quitGame;
seed();render();
})();
