const app=document.getElementById('app');
let state={screen:'home',mode:'classic',round:0,roster:[],teamSkip:1,decadeSkip:1,combo:null,options:[],selected:null,record:null,season:[],stats:null};
const positions=['PG','SG','SF','PF','C'];
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const teamName=id=>TEAMS[id]||id;
const key=(team,decade)=>team+'|'+decade;
const save=()=>localStorage.setItem('rtg82_exact',JSON.stringify(state));
const load=()=>{try{const s=JSON.parse(localStorage.getItem('rtg82_exact'));if(s&&s.screen)state=s}catch(e){}};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function playersFor(team,decade){return PLAYERS.filter(p=>p.team===team&&p.decade===decade&&!state.roster.some(r=>r.name===p.name&&r.team===p.team))}
function randomCombo(){let k=VALID_COMBOS[Math.floor(Math.random()*VALID_COMBOS.length)].split('|');return {team:k[0],decade:k[1]}}
function optionsFor(c){let x=playersFor(c.team,c.decade);return shuffle(x).slice(0,Math.min(5,x.length))}
function start(){state={screen:'draft',mode:state.mode,round:0,roster:[],teamSkip:1,decadeSkip:1,combo:null,options:[],selected:null,record:null,season:[],stats:null};spin(true)}
function spin(initial=false){if(state.round>=5)return;state.selected=null;state.combo=randomCombo();state.options=optionsFor(state.combo);if(state.options.length<3){return spin(initial)};state.screen='draft';save();render()}
function skipTeam(){if(!state.teamSkip)return;const decade=state.combo.decade,old=state.combo.team;let teams=shuffle(Object.keys(TEAMS).filter(t=>t!==old&&PLAYERS.filter(p=>p.team===t&&p.decade===decade&&!state.roster.some(r=>r.name===p.name&&r.team===p.team)).length>=3));if(!teams.length)return;state.teamSkip=0;state.combo={team:teams[0],decade};state.options=optionsFor(state.combo);state.selected=null;save();render()}
function skipDecade(){if(!state.decadeSkip)return;const team=state.combo.team,old=state.combo.decade;let ds=shuffle(DECADES.filter(d=>d!==old&&PLAYERS.filter(p=>p.team===team&&p.decade===d&&!state.roster.some(r=>r.name===p.name&&r.team===p.team)).length>=3));if(!ds.length)return;state.decadeSkip=0;state.combo={team,decade:ds[0]};state.options=optionsFor(state.combo);state.selected=null;save();render()}
function selectPlayer(i){state.selected=state.options[i];render()}
function confirmPick(pos){if(!state.selected||!positions.includes(pos))return;state.roster.push({...state.selected,slot:pos});state.selected=null;state.round++;if(state.round>=5)state.screen='lineup';else spin();save();render()}
function statRating(p){return Math.max(1,Math.min(99,Math.round(45+p.ppg*1.05+p.rpg*.75+p.apg*.95+p.spg*2.4+p.bpg*2.5)))}
function teamPower(){let base=state.roster.reduce((s,p)=>s+statRating(p),0)/5;let stats=['ppg','rpg','apg','spg','bpg'].map(k=>state.roster.reduce((s,p)=>s+p[k],0));let balance=(Math.min(...stats)/Math.max(...stats));let posBonus=new Set(state.roster.map(p=>p.slot)).size===5?4:0;return Math.round(base+balance*10+posBonus)}
function winProbability(){let power=teamPower();let z=(power-77)/7;return 1/(1+Math.exp(-z))}
function simulate(){let prob=winProbability();let wins=0, games=[];for(let i=0;i<82;i++){let difficulty=.965-Math.min(.025,i/82*.025);let p=Math.max(.015,Math.min(.995,prob*difficulty));let win=Math.random()<p;if(win)wins++;games.push(win)};if(powerPerfect())wins=Math.min(82,wins+Math.random()<.38?1:0);return games.map((win,i)=>({n:i+1,win,score:win?randomScore(true):randomScore(false),opponent:OPPONENTS[i%OPPONENTS.length]})).map(g=>g)}
function randomScore(win){let a=Math.round(108+Math.random()*22),b=Math.round(96+Math.random()*24);if(win&&a<=b)a=b+Math.ceil(Math.random()*9);if(!win&&a>=b)b=a+Math.ceil(Math.random()*9);return a+'-'+b}
const OPPONENTS=['Boston Celtics','New York Knicks','Milwaukee Bucks','Cleveland Cavaliers','Miami Heat','Orlando Magic','Philadelphia 76ers','Indiana Pacers','Chicago Bulls','Detroit Pistons','Atlanta Hawks','Charlotte Hornets','Toronto Raptors','Brooklyn Nets','Washington Wizards','Denver Nuggets','Oklahoma City Thunder','Minnesota Timberwolves','Phoenix Suns','LA Clippers','Los Angeles Lakers','Golden State Warriors','Sacramento Kings','Dallas Mavericks','Houston Rockets','San Antonio Spurs','New Orleans Pelicans','Memphis Grizzlies','Portland Trail Blazers','Utah Jazz'];
function powerPerfect(){return teamPower()>=94}
function runSeason(){state.season=simulate();state.record=state.season.filter(g=>g.win).length;state.stats={power:teamPower(),prob:Math.round(winProbability()*100)};state.screen='result';save();render()}
function reset(){localStorage.removeItem('rtg82_exact');state={screen:'home',mode:'classic',round:0,roster:[],teamSkip:1,decadeSkip:1,combo:null,options:[],selected:null,record:null,season:[],stats:null};render()}
function shell(content){app.innerHTML=`<header><div class="logo" onclick="reset()"><span>82–0</span><small>ROAD TO GREATNESS</small></div><div class="headerRight"><span class="liveDot"></span><span>CLASSIC NBA DRAFT</span><button class="new" onclick="reset()">NEW GAME</button></div></header><main>${content}</main>`}
function home(){shell(`<section class="home"><div class="pill">THE ULTIMATE FIVE-MAN DRAFT</div><h1>Can you build a team<br>good enough to go <i>82–0?</i></h1><p class="lead">Spin for a random franchise and decade. Draft one player each round. Complete your starting five, then put them through the full 82-game season.</p><div class="modeWrap"><button class="mode ${state.mode==='classic'?'on':''}" onclick="state.mode='classic';render()"><strong>CLASSIC</strong><span>Player stats visible</span></button><button class="mode ${state.mode==='hoopiq'?'on':''}" onclick="state.mode='hoopiq';render()"><strong>HOOPIQ</strong><span>Player stats hidden</span></button></div><button class="primary huge" onclick="start()">START DRAFT <b>→</b></button><div class="rulebar"><div><b>5</b><span>ROUNDS</span></div><div><b>1</b><span>TEAM SKIP</span></div><div><b>1</b><span>DECADE SKIP</span></div><div><b>82</b><span>GAMES</span></div></div><div class="how"><span>HOW IT WORKS</span><div>SPIN <b>→</b> SEE PLAYERS <b>→</b> PICK <b>→</b> POSITION <b>→</b> BUILD FIVE <b>→</b> SIMULATE 82</div></div></section>`)}
function draft(){const c=state.combo, round=state.round+1;const selected=state.selected;let cards=state.options.map((p,i)=>`<button class="playerCard ${selected===p?'chosen':''}" onclick="selectPlayer(${i})"><div class="cardTop"><div><small>${p.pos}</small><h3>${esc(p.name)}</h3></div><strong>${statRating(p)}</strong></div>${state.mode==='classic'?`<div class="stats"><span><b>${p.ppg.toFixed(1)}</b>PPG</span><span><b>${p.rpg.toFixed(1)}</b>RPG</span><span><b>${p.apg.toFixed(1)}</b>APG</span><span><b>${p.spg.toFixed(1)}</b>SPG</span><span><b>${p.bpg.toFixed(1)}</b>BPG</span></div>`:`<div class="hidden">HOOPIQ · STATS HIDDEN</div>`}<div class="selectLabel">${selected===p?'PLAYER SELECTED · CHOOSE POSITION':'SELECT PLAYER'} <span>→</span></div></button>`).join('');shell(`<section class="draftHead"><div><div class="pill">ROUND ${round} OF 5</div><h1>${teamName(c.team)} <em>·</em> ${c.decade}</h1><p>Spin result locked. Choose one player from this team and era.</p></div><div class="skipBox"><button onclick="skipTeam()" ${state.teamSkip?'':'disabled'}>TEAM SKIP <b>${state.teamSkip}</b></button><button onclick="skipDecade()" ${state.decadeSkip?'':'disabled'}>DECADE SKIP <b>${state.decadeSkip}</b></button></div></section><section class="progress">${positions.map((pos,i)=>`<div class="slot ${state.roster[i]?'filled':''}"><small>${pos}</small><strong>${state.roster[i]?esc(state.roster[i].name):'EMPTY'}</strong></div>`).join('')}</section><div class="draftTools"><span><b>AVAILABLE PLAYERS</b> · ${state.options.length} SHOWN</span><span>MODE: <b>${state.mode.toUpperCase()}</b></span></div><section class="cards">${cards}</section>${selected?positionPicker(selected):''}`)}
function positionPicker(p){let eligible=positions.filter(pos=>p.pos.split('/').includes(pos));return `<div class="overlay"><div class="picker"><button class="close" onclick="state.selected=null;render()">×</button><div class="pill">LOCK IN PICK</div><h2>${esc(p.name)}</h2><p>Choose the position you want this player to occupy.</p><div class="positionBtns">${eligible.map(pos=>`<button onclick="confirmPick('${pos}')"><strong>${pos}</strong><span>LOCK PLAYER</span></button>`).join('')}</div></div></div>`}
function lineup(){shell(`<section class="lineup"><div class="pill">DRAFT COMPLETE</div><h1>YOUR STARTING FIVE</h1><p>Five picks. Five positions. No take-backs.</p><div class="five">${positions.map(pos=>{let p=state.roster.find(x=>x.slot===pos);return `<div class="fiveRow"><span>${pos}</span><div><b>${esc(p.name)}</b><small>${p.pos} · ${teamName(p.team)} · ${p.decade}</small></div><strong>${statRating(p)}</strong></div>`}).join('')}</div><button class="primary huge" onclick="runSeason()">SIMULATE 82 GAMES <b>→</b></button></section>`)}
function result(){let r=state.record,perfect=r===82;let recent=state.season.slice(-8);shell(`<section class="result ${perfect?'perfect':''}"><div class="pill">SEASON COMPLETE</div><h1>${perfect?'PERFECT SEASON':'FINAL RECORD'}</h1><div class="record"><strong>${r}</strong><i>–</i><strong>${82-r}</strong></div><div class="recordLabels"><span>WINS</span><span>LOSSES</span></div><div class="resultGrid"><div><b>${state.stats.power}</b><span>TEAM POWER</span></div><div><b>${state.stats.prob}%</b><span>WIN PROJECTION</span></div><div><b>82</b><span>GAMES PLAYED</span></div></div><div class="seasonBox"><div class="seasonTitle">LAST 8 GAMES</div>${recent.map(g=>`<div class="game ${g.win?'W':'L'}"><span>GAME ${g.n}</span><b>${g.win?'W':'L'}</b><span>vs ${g.opponent}</span><strong>${g.score}</strong></div>`).join('')}</div><p class="resultMsg">${perfect?'YOU DID IT. EVERY GAME. 82–0.':'The perfect season is still out there. Draft again and build a stronger five.'}</p><div class="actions"><button class="primary" onclick="start()">PLAY AGAIN <b>↻</b></button><button class="secondary" onclick="state.screen='lineup';render()">VIEW LINEUP</button></div></section>`)}
function render(){if(state.screen==='home')home();else if(state.screen==='draft')draft();else if(state.screen==='lineup')lineup();else result()}
load();render();
